server {
    listen 80 default_server;
    server_name alice-ctf.local _;

    root /var/www/html/alice-ctf.local;
    index index.html;
    charset utf-8;

    location / {
        try_files $uri $uri/ =404;
    }

    # Uncomment once the Flask API is running
    # location /submit {
    #     proxy_pass         http://127.0.0.1:5000/submit;
    #     proxy_set_header   Host $host;
    #     proxy_set_header   X-Real-IP $remote_addr;
    #     proxy_read_timeout 10s;
    # }
}
